# Generated by Django 3.2.8 on 2021-10-31 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['nomi'],
            },
        ),
        migrations.CreateModel(
            name='Gullar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=300)),
                ('narxi', models.IntegerField()),
                ('rasmi', models.CharField(max_length=400)),
                ('kategoriya', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shablon.kategoriya')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
